### ISSUE TITLE
Improve number parsing

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/query-string#263]
https://github.com/sindresorhus/query-string/pull/241

**Comment by RocktimSaikia** [comment]
@sindresorhus  I went through this #241 pr and did a few tests and there was no issue regarding number parsing actually, I tried everything and could not re-create anything related to that issue stated by on that pr. 

What I did found is that he was probably running some test cases and the `key` of the expected value was not in `quotes` meaning he was probably testing it as a number so when running the tests the compiler treated it as a number just like it should.

If you run the following test, it will recreate that issue and generate an error saying the expected value is 19200000000000 since the expected object key is a number which is true.

```js
test('handle number pusring correctly with math operands', t => {
	t.deepEqual(queryString.parse('192e11=bar'), {192e11: 'bar'});
});
```

But when you add the quotes to the expected object key and turn it into a string then the tests work fine. So basically there is no such issue regarding number parsing.

**Comment by RocktimSaikia** [comment]
I was not able to re-create this issue!

Both of the following works just fine as it should be.
```
queryString.parse('192e11=bar')
//=> {'192e11' : bar}

queryString.parse('bar=192e11')
//=> {bar : '192e11'}
```
Did misunderstood the issue ?
// @sindresorhus

**Comment by sindresorhus** [comment]
How about stringify?

**Comment by sindresorhus** [comment]
But that's good. Then this issue is just about submitting some tests to confirm the existing behavior.

**Comment by RocktimSaikia** [comment]
@sindresorhus stringify is working too. I think his pr was kind of misleading cause here is an assumption on what he probably did.
He probably created a test such as 
```js
	t.deepEqual(queryString.parse('192e11=bar'), {192e11: 'bar'});
```
and left the expected key as a number, not as a string and therefore when he ran the test it threw an error saying that it is expecting 1920000000000000000000000 as it should since it is expecting a number.

But yeah not issue on the module. I can write some tests on that later if needed!

**Comment by sindresorhus** [comment]
> I can write some tests on that later if needed!

That would be amazing 👍🏻
