### ISSUE TITLE
queryString.exclude an hash url is not expected

### ISSUE THREAD

**Issue by xmsz** [sindresorhus/query-string#318]
```
queryString.exclude('https://xxx.com?a=b#/home', ['a'])
```

expect:

```
https://xxx.com#/home
```

result
```
https://xxx.com?a=b#%2Fhome
```

**Comment by sindresorhus** [comment]
Confirmed.

---

// @Richienb

**Comment by Richienb** [comment]
That's intended behaviour. `query-string` is automatically uri-encoding the slash because the `encode` option is `true` by default. Likewise, the following yields the intended behaviour:

```js
queryString.exclude('https://xxx.com?a=b#/home', ['a'], {encode: false});
//=> https://xxx.com#/home
```

However this option also disables encoding of the query parameters because of how it checks the same `encode` option.

@sindresorhus Should we add seperate `encodeQuery` and `encodeFragmentIdentifier` options to `exports.stringifyUrl`? If so, should `encode` still be kept as a shorthand for these 2 options or removed entirely?

**Comment by sindresorhus** [comment]
@Richienb I don't think it's something people would need outside of `query-string`. So my preference would be to expose both those options internally for `.exclude()` could use them, but keep it as `encode` publicly.
